# Generated by Django 5.1.7 on 2025-04-09 06:00

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('summary', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('skills', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('previous_work', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('degree', models.CharField(blank=True, max_length=200)),
                ('school', models.CharField(blank=True, max_length=200)),
                ('university', models.CharField(blank=True, max_length=200)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/')),
                ('additional_sections', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
