# Generated by Django 5.1.7 on 2025-04-09 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CV_Gen', '0002_alter_profile_degree'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='degree',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='previous_work',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='school',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='skills',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='summary',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='university',
        ),
    ]
