# Generated by Django 5.1.7 on 2025-04-09 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CV_Gen', '0004_profile_degree_profile_previous_work_profile_school_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='degree',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='previous_work',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='school',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='skills',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='summary',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='university',
        ),
    ]
